Adding adas flag to makefile but unit tests don't recognize it.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -15,6 +15,7 @@ CUDA_ARCH=70
 
 USE_MPI=
 USE_LUA=
+USE_ADAS=
 # Lua link to static library
 CONF_LUA_LIB=luajit-5.1
 
@@ -49,6 +50,7 @@ CUDA_ARCH                  CUDA architecture flag to specify compute capability.
 
 --use-mpi                  [no] Build MPI-dependent code
 --use-lua                  [no] Build Lua dependent code
+--use-adas                 [no] Build adas dependent code
 
 Library Includes and Locations
 
@@ -172,7 +174,11 @@ do
    --cudamath-libdir)
       [ -n "$value" ] || die "Missing value in flag $key."
       CUDAMATH_LIBDIR="$value"
-      ;;   
+      ;;
+   --use-adas)
+      [ -n "$value" ] || die "Missing value in flag $key."
+      USE_ADAS="$value"
+      ;;  
    *)
       die "Error: Unknown flag: $1"
       ;;
@@ -192,6 +198,13 @@ then
     USE_LUA=1
 else
     USE_LUA=
+fi
+
+if [ "$USE_ADAS" = "yes" ]
+then
+    USE_ADAS=1
+else
+    USE_ADAS=
 fi
 
 # Default lapack include and libraries: we prefer linking to static library
