Create a nccl_comm object. Currently it can only send/recv a gkyl_array. Unit test passes. There's some redundancy on how to treat the blocking send/recv, as the communicator itself is nonblocking (I think this should be the default). But for now I've added wait/sync methods in the blocking send/recv to make it behave like their MPI counterparts.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -48,6 +48,7 @@ CUDA_ARCH                  CUDA architecture flag to specify compute capability.
                            Default is $HOME/gkylsoft/
 
 --use-mpi                  [no] Build MPI-dependent code
+--use-nccl                 [no] Build NCCL-dependent code
 --use-lua                  [no] Build Lua dependent code
 
 Library Includes and Locations
@@ -60,6 +61,9 @@ Library Includes and Locations
 
 --mpi-inc                  Location of MPI headers
 --mpi-lib                  Location to MPI library
+
+--nccl-inc                 Location of NCCL headers
+--nccl-lib                 Location to NCCL library
 
 --lua-inc                  Location of Lua headers
 --lua-lib                  Location to Lua library
@@ -157,6 +161,18 @@ do
       [ -n "$value" ] || die "Missing value in flag $key."
       CONF_MPI_LIB_DIR="$value"
       ;;
+   --use-nccl)
+      [ -n "$value" ] || die "Missing value in flag $key."
+      USE_NCCL="$value"
+      ;;       
+   --nccl-inc)
+      [ -n "$value" ] || die "Missing value in flag $key."
+      CONF_NCCL_INC_DIR="$value"
+      ;;
+   --nccl-lib)
+      [ -n "$value" ] || die "Missing value in flag $key."
+      CONF_NCCL_LIB_DIR="$value"
+      ;;
    --use-lua)
       [ -n "$value" ] || die "Missing value in flag $key."
       USE_LUA="$value"
@@ -185,6 +201,13 @@ then
     USE_MPI=1
 else
     USE_MPI=
+fi
+
+if [ "$USE_NCCL" = "yes" ]
+then
+    USE_NCCL=1
+else
+    USE_NCCL=
 fi
 
 if [ "$USE_LUA" = "yes" ]
@@ -236,6 +259,10 @@ SUPERLU_LIB=$SUPERLU_LIB
 USE_MPI=$USE_MPI
 CONF_MPI_INC_DIR=$CONF_MPI_INC_DIR
 CONF_MPI_LIB_DIR=$CONF_MPI_LIB_DIR
+
+USE_NCCL=$USE_NCCL
+CONF_NCCL_INC_DIR=$CONF_NCCL_INC_DIR
+CONF_NCCL_LIB_DIR=$CONF_NCCL_LIB_DIR
 
 USE_LUA=$USE_LUA
 CONF_LUA_INC_DIR=$CONF_LUA_INC_DIR
